FROM thomasjpfan/ubuntu-python-systemd:18.04-py2

LABEL version="1.1.0"

ENV ANSIBLE_VERSION 2.6.1
ENV TESTINFRA_VERSION 1.14.1
ENV ANSIBLE_LINT_VERSION 3.4.23

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python-setuptools python-pip build-essential libssl-dev libffi-dev  && \
    pip install -U wheel && \
    pip install -U ansible==${ANSIBLE_VERSION} \
    testinfra==${TESTINFRA_VERSION} \
    ansible-lint==${ANSIBLE_LINT_VERSION} \
    pyOpenSSL && \
    apt-get remove -y --auto-remove python-setuptools python-pip build-essential libssl-dev libffi-dev && \
    rm -Rf /var/lib/apt/lists/* && \
    rm -Rf /usr/share/doc && rm -Rf /usr/share/man && \
    apt-get clean && \
    mkdir -p  /etc/ansible/roles/role_to_test && \
    echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

COPY cli.sh /usr/local/bin/cli

WORKDIR /etc/ansible/roles/role_to_test
