FROM thomasjpfan/ubuntu-python-systemd:18.04-py3

LABEL version="1.1.0"

ENV ANSIBLE_VERSION 2.6.1
ENV TESTINFRA_VERSION 1.14.1
ENV ANSIBLE_LINT_VERSION 3.4.23

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-setuptools python3-pip && \
    pip3 install -U ansible==${ANSIBLE_VERSION} \
    testinfra==${TESTINFRA_VERSION} \
    ansible-lint==${ANSIBLE_LINT_VERSION} \
    pyOpenSSL && \
    apt-get remove -y --auto-remove python3-setuptools python3-pip && \
    rm -Rf /var/lib/apt/lists/* && \
    rm -Rf /usr/share/doc && rm -Rf /usr/share/man && \
    apt-get clean && \
    mkdir -p  /etc/ansible/roles/role_to_test && \
    echo "[local]\nlocalhost ansible_connection=local\n[local:vars]\nansible_python_interpreter=/usr/bin/python3" > /etc/ansible/hosts

COPY cli.sh /usr/local/bin/cli

WORKDIR /etc/ansible/roles/role_to_test
